---
rest_api_id: 123gfg3g4
swagger: "2.0"
info:
  version: "2016-03-26T21:15:49Z"
  title: "LambdaMicroservice"

  description: Sample swagger API definition used to develop the module.
host: "nnnnnnnnn.execute-api.us-east-1.amazonaws.com"
basePath: "/Dev"
schemes:
- "https"
resources:
- resource_id: iuy34yiuy43
  parent_id: h23guiyds7
  path_part: ingestData:
  http_methods:
  - http_method: get
    responses:
    - response_code: "200"
      description: "OK response"
      headers:
        Access-Control-Allow-Origin:
          type: "string"
    security:
    - sigv4: []
    x-amazon-apigateway-integration:
      responses:
        .*:
          statusCode: "200"
          responseParameters:
            method.response.header.Access-Control-Allow-Origin: "'*'"
      uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:000000000000:function:ingestData/invocations"
      httpMethod: "POST"
      type: "aws"
  - http_method: post
    produces:
    - "application/json"
    responses:
    - response_code: "200"
      description: "200 response"
      schema:
        $ref: "#/definitions/Empty"
    x-amazon-apigateway-integration:
      responses:
        default:
          statusCode: "200"
      uri: "http://some.external-endpoint.com
      httpMethod: "POST"
      type: "http"
securityDefinitions:
  sigv4:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "awsSigv4"
definitions:
  Empty:
    type: "object"
